version: '3'


services:
  backend:
    build:
      context: .
      dockerfile: inforce/docker/python/Dockerfile
    command: gunicorn inforce.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./inforce:/app
    ports:
      - 8000:8000
    container_name: backend
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - .:/app
      - ./inforce/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1141:80
    container_name: nginx
    networks:
      - backend
    depends_on:
      - backend

  db:
    image: mysql:latest
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inforce_attempt_2
    container_name: db
    volumes:
      - ./docker/db:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge
